# Site settings
title: Hannah Barudin
email: hbarudin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This will be my awesome site and more info will go here soon. From the original config:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hannahbarudin.com" # the base hostname & protocol for your site
twitter_username: hbarudin
github_username:  hbarudin

# Build settings
markdown: kramdown
